### ISSUE TITLE
Include original Github-Environment-Cleaner License

### ISSUE THREAD

**Issue by VishalRamesh50** [chathurabuddi/github-config#1]
Hello 👋. I'm glad you found my script useful enough to include in your repo. However, I would appreciate it if you included the original license in your `github-environment-cleaner` directory in order to respect the license conditions. A copy can be found here: https://github.com/VishalRamesh50/Github-Environment-Cleaner/blob/master/LICENSE. Thank you.

**Comment by chathurabuddi** [comment]
Hi @VishalRamesh50, I have missed it, and thanks for reaching out. Just added the LICENCE to the subdirectory and your name was added to the man LICENCE as well.
